### ISSUE TITLE
Relative import paths not resolved when built

### ISSUE THREAD

**Issue by samzhao** [sourcescript/alt-notify#10] opened 2015-06-08 20:21 UTC
Hi,

I'm having difficulty using the built file `alt-notify.js` under the dist directory as it did not have the relative paths resolved, thus causing errors like this:

```
Module not found: Error: Cannot resolve 'file' or 'directory' ./NotifyActions in /Users/username/dev/react-webpack/node_modules/alt-notify/dist
```

Please help look into it. Thanks!

**Comment by srph** [comment] 2015-06-09 11:21
Sorry for the late reply. I'll take a look.

What bundler are you using, by the way? 

**Update**: I can't reproduce the issue as the examples are working. But I'm still thinking of different ways.

**Comment by samzhao** [comment] 2015-06-09 17:19
@srph I'm using webpack with `babel-loader`.

Actually, I get the same errors even without using it within my project. Here's how I first encountered the problem:
1. I `git clone` the project, `npm install && npm run build`. No errors so far, except the file inside of dist has changed, not sure if that's the expected behaviour.
2. `cd examples/basic` then `npm start`, error right off the bat "missing script: install". I go into package.json under `examples/basic/` and change `npm run install` to `npm install` and run `npm start` again.
3. Now I get this error:

```
Error: Cannot find module './NotifyActions' from '/Users/user/dev/alt-notify/dist'
    at /Users/user/dev/alt-notify/examples/basic/node_modules/browserify/node_modules/resolve/lib/async.js:55:21
    at load (/Users/user/dev/alt-notify/examples/basic/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/user/dev/alt-notify/examples/basic/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /Users/user/dev/alt-notify/examples/basic/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at Object.oncomplete (fs.js:107:15)

npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v0.10.24
npm ERR! npm  v2.7.1
npm ERR! code ELIFECYCLE
npm ERR! twbs@1.0.0 build: `browserify -t [babelify --stage 0] --extension=.jsx . > bundle.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the twbs@1.0.0 build script 'browserify -t [babelify --stage 0] --extension=.jsx . > bundle.js'.
npm ERR! This is most likely a problem with the twbs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     browserify -t [babelify --stage 0] --extension=.jsx . > bundle.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls twbs
npm ERR! There is likely additional logging output above.
```

**Comment by srph** [comment] 2015-06-13 07:58
This must be due to my babel build. Lemme fix this. Sorry about that -- busy at work.

**Comment by srph** [comment] 2015-06-13 08:34
Should be fixed by https://github.com/sourcescript/alt-notify/commit/210ad01f9ad5a9876de8bebb53da6104a973a812 / `v0.3.4`.

Thanks a lot, @samzhao for pointing this out.

**Closed as completed** 2015-06-13 08:35 UTC
